### ISSUE TITLE
Why i am getting Null in Uri.getPath()

### ISSUE THREAD

**Issue by PraveenGaur1987** [miskoajkula/PHP-MYSQL-IMAGE-UPLOAD#2]
I am getting this issue please help why it giving null and also tell me how to get  dynamically. imageimage_name = "testing123.jpg";
        file = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
                + File.separator + image_name

****Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                                         at com.example.dssandroid.projectimage.MainActivity$Encode_image.doInBackground(MainActivity.java:76)
                                                                                         at com.example.dssandroid.projectimage.MainActivity$Encode_image.doInBackground(MainActivity.java:72)
                                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)****

**Comment by deysarkarswarup** [comment]
Give permission to access your storage. Then it will work.

**Comment by deysarkarswarup** [comment]
//add the following methods and call them inside a if condition like->> 
if (!checkPermission()) {
                    requestPermission(); // Code for permission
                }

private boolean checkPermission() {
        int result = ContextCompat.checkSelfPermission(MainActivity.this, android.Manifest.permission.WRITE_EXTERNAL_STORAGE);
        if (result == PackageManager.PERMISSION_GRANTED) {
            return true;
        } else {
            return false;
        }
    }

    private void requestPermission() {
        if (ActivityCompat.shouldShowRequestPermissionRationale(MainActivity.this, android.Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
            Toast.makeText(MainActivity.this, "Write External Storage permission allows us to save files. Please allow this permission in App Settings.", Toast.LENGTH_LONG).show();
        } else {
            ActivityCompat.requestPermissions(MainActivity.this, new String[]{android.Manifest.permission.WRITE_EXTERNAL_STORAGE}, PERMISSION_REQUEST_CODE);
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
        switch (requestCode) {
            case PERMISSION_REQUEST_CODE:
                if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                Log.e("value", "Permission Granted, Now you can use local drive .");
            } else {
                Log.e("value", "Permission Denied, You cannot use local drive .");
            }
            break;
        }
    }
